# Generated by Django 3.0.5 on 2021-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='articles/thumbnails/%Y/%m/%d', verbose_name='Thumbnail(850x550)'),
        ),
    ]
