# Generated by Django 3.0.5 on 2021-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210104_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
