# Generated by Django 3.0.5 on 2021-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerfooter',
            name='image',
            field=models.ImageField(upload_to='banner/footer', verbose_name='Image(730x90)'),
        ),
        migrations.AlterField(
            model_name='bannerfooter',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bannerheader',
            name='image',
            field=models.ImageField(upload_to='banner/header', verbose_name='Image(730x90)'),
        ),
        migrations.AlterField(
            model_name='bannerheader',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bannersidebar',
            name='image',
            field=models.ImageField(upload_to='banner/sidebar', verbose_name='Image(300x300)'),
        ),
        migrations.AlterField(
            model_name='bannersidebar',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
